﻿name: Deploy with AWS CDK

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ env.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          cd infra
          yarn

      - name: Build and deploy AWS CDK app
        run: |
          cd infra
          yarn cdk deploy
